name = "Fuzzys-enhanced-vanilla"
author = "Fuzzyeureka"
version = "7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fbdb5b4350cdf925c61c2d8f5d7eac64ad000e15910ad01fd7d80a666e10e81"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
