name = "Fuzzys-enhanced-vanilla"
author = "Fuzzyeureka"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "355881175cfdc33b2cc4dc888aa4b6be54e7403a35f87de25b7a400aaf98718f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
