name = "Fuzzys-enhanced-vanilla"
author = "Fuzzyeureka"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c7969a95b4bad12558d661e731c65837f24ad327e866f5464d908b3ea0850c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
